Repository muhammadfajri-tif/tubes-03-1b, pull requests merged in 2023-12, with the labels that each got.

#4 Add Modules
  .gitignore
  include/boolean.h
  lib/board.c
  lib/board.h
  lib/bot.c
  lib/bot.h
  lib/game.c
  lib/game.h
  lib/menu.c
  lib/menu.h
  lib/score.c
  lib/score.h
  main.c
Labels: enhancement

#5 Add Rematch Features
  lib/menu.c
  lib/menu.h
Labels: enhancement

#6 Update menu.c buat back
  lib/menu.c
Labels: good first issue

#14 Add support multi operating system
  include/currentos.h
  lib/bot.c
  lib/bot.h
  lib/game.c
  lib/menu.c
Labels: enhancement, help wanted
